export const triviaAnswer = [["¿Qué órgano del cuerpo humano es responsable de bombear sangre?", "Pulmones", "Hígado", "Corazón", "Cerebro", 3],
["¿Cómo se llama el proceso por el cual las plantas convierten la luz en energía?", "Fotosíntesis", "Respiración celular", "Digestión", "Osmosis", 1],
["¿Cuál es el elemento químico con el símbolo 'O'?", "Oro", "Oxígeno", "Osmio", "Oxalato", 2],
["¿Qué científico propuso la teoría de la relatividad?", "Nikola Tesla", "Albert Einstein", "Isaac Newton", "Marie Curie", 2],
["¿Qué planeta es conocido como el 'Planeta Rojo'?", "Venus", "Marte", "Júpiter", "Saturno", 2],
["¿Cuál es el mamífero más grande del mundo?", "Elefante africano", "Orca", "Ballena azul", "Hipopótamo", 3],
["¿Cuál es la unidad básica de la vida?", "Átomo", "Molécula", "Célula", "Organoide", 3],
["¿Cuál es la temperatura de congelación del agua en grados Celsius?", "-1°C", "0°C", "32°C", "100°C", 2],
["¿Qué gas es necesario para la respiración humana?", "Nitrógeno", "Oxígeno", "Hidrógeno", "Dióxido de carbono", 2],
["¿Qué tipo de energía utiliza una batería?", "Energía térmica", "Energía química", "Energía cinética", "Energía solar", 2],
["¿Cuántos planetas tiene nuestro sistema solar?", "7", "8", "9", "10", 2],
["¿Qué instrumento mide los terremotos?", "Barómetro", "Termómetro", "Sismógrafo", "Anemómetro", 3],
["¿Cuál es la fórmula química del agua?", "CO2", "H2O", "NaCl", "O2", 2],
["¿Qué hueso es el más largo del cuerpo humano?", "Húmero", "Fémur", "Tibia", "Radio", 2],
["¿Qué rama de la ciencia estudia los seres vivos?", "Física", "Química", "Biología", "Geología", 3],
["¿Qué gas es el más abundante en la atmósfera terrestre?", "Oxígeno", "Nitrógeno", "Dióxido de carbono", "Hidrógeno", 2],
["¿Qué órgano del cuerpo humano se encarga de filtrar la sangre?", "Pulmones", "Riñones", "Corazón", "Hígado", 2],
["¿Qué descubrimiento es atribuido a Alexander Fleming?", "Vacuna contra la rabia", "Penicilina", "Teoría de la relatividad", "Genoma humano", 2],
["¿Qué fenómeno óptico se produce por la refracción de la luz en gotas de agua?", "Aurora boreal", "Arcoíris", "Espejismo", "Eclipse", 2],
["¿Qué planeta tiene un sistema de anillos prominente?", "Júpiter", "Saturno", "Urano", "Neptuno", 2],
["¿Cuál es el órgano más grande del cuerpo humano?", "Hígado", "Piel", "Corazón", "Pulmones", 2],
["¿Qué parte de la planta se encarga de la fotosíntesis?", "Raíces", "Hojas", "Flores", "Tallos", 2],
["¿Qué tipo de onda es la luz?", "Longitudinal", "Transversal", "Sonora", "Mecánica", 2],
["¿Cuál es el planeta más cercano al Sol?", "Mercurio", "Venus", "Tierra", "Marte", 1],
["¿Qué científica ganó dos premios Nobel?", "Rosalind Franklin", "Marie Curie", "Ada Lovelace", "Jane Goodall", 2],
["¿Qué animal es conocido por ser el más rápido en tierra?", "León", "Antílope", "Guepardo", "Canguro", 3],
["¿Cómo se llama la ciencia que estudia las estrellas?", "Geología", "Astronomía", "Biología", "Física", 2],
["¿Qué metal es líquido a temperatura ambiente?", "Hierro", "Plata", "Mercurio", "Cobre", 3],
["¿Qué tejido conecta los músculos con los huesos?", "Cartílago", "Ligamentos", "Tendones", "Epidermis", 3],
["¿Qué velocidad alcanza la luz en el vacío?", "300 km/s", "300,000 km/s", "3,000 km/s", "30,000 km/s", 2],
["¿Qué planeta tiene el día más largo?", "Venus", "Tierra", "Marte", "Júpiter", 1],
["¿Cuál es el componente principal del Sol?", "Helio", "Oxígeno", "Carbono", "Hidrógeno", 4],
["¿Qué capa de la atmósfera contiene el ozono?", "Exosfera", "Estratosfera", "Mesosfera", "Troposfera", 2],
["¿Qué número atómico tiene el hidrógeno?", "0", "1", "2", "8", 2],
["¿Qué fuerza mantiene a los planetas en órbita alrededor del Sol?", "Electromagnética", "Nuclear", "Gravitacional", "Magnética", 3],
["¿Qué tipo de sangre es el donante universal?", "A", "B", "AB", "O", 4],
["¿Qué órgano produce la insulina?", "Hígado", "Páncreas", "Riñón", "Estómago", 2],
["¿Cuál es el animal más grande que ha existido?", "Tyrannosaurus rex", "Ballena azul", "Elefante mamut", "Megaterio", 2],
["¿Qué gas es el principal causante del efecto invernadero?", "Oxígeno", "Metano", "Dióxido de carbono", "Ozono", 3],
["¿Qué órgano humano está más relacionado con la memoria?", "Cerebro", "Corazón", "Hígado", "Pulmones", 1],
["¿Qué país fue el primero en enviar un satélite al espacio?", "Estados Unidos", "Rusia", "China", "Reino Unido", 2],
["¿Cómo se llama el estudio de los fósiles?", "Biología", "Geología", "Paleontología", "Antropología", 3],
["¿Qué glándula en el cerebro regula el sueño?", "Hipófisis", "Epífisis", "Tálamo", "Amígdala", 2],
["¿Qué mineral es esencial para los huesos?", "Hierro", "Calcio", "Potasio", "Magnesio", 2],
["¿Qué planeta es el más grande del sistema solar?", "Tierra", "Júpiter", "Saturno", "Urano", 2],
["¿Qué tipo de roca se forma por enfriamiento de lava?", "Metamórfica", "Ígnea", "Sedimentaria", "Volcánica", 2],
["¿Qué animal pone huevos pero es mamífero?", "Ornitorrinco", "Pingüino", "Murciélago", "Canguro", 1],
["¿Qué unidad se usa para medir la frecuencia?", "Hertz", "Pascal", "Newton", "Voltio", 1],
["¿Qué molécula transporta el oxígeno en la sangre?", "Insulina", "Hemoglobina", "Glucosa", "ADN", 2]
["¿Qué partícula subatómica tiene carga negativa?", "Protón", "Neutrón", "Electrón", "Quark", 3],
["¿Cuál es el planeta más grande del sistema solar?", "Tierra", "Júpiter", "Saturno", "Urano", 2],
["¿Qué científico formuló las leyes del movimiento?", "Albert Einstein", "Isaac Newton", "Galileo Galilei", "Marie Curie", 2],
["¿Qué tipo de energía se obtiene del núcleo del átomo?", "Energía solar", "Energía térmica", "Energía nuclear", "Energía cinética", 3],
["¿Qué es el ADN?", "Ácido ribonucleico", "Adenosina", "Ácido desoxirribonucleico", "Aminoácido", 3],
["¿Qué unidad se utiliza para medir la intensidad de la corriente eléctrica?", "Amperio", "Voltio", "Ohmio", "Watt", 1],
["¿Cuál es el metal más abundante en la corteza terrestre?", "Hierro", "Aluminio", "Cobre", "Plata", 2],
["¿Qué planeta está más cerca del Sol?", "Venus", "Mercurio", "Tierra", "Marte", 2],
["¿Qué descubrimiento hizo Galileo Galilei con su telescopio?", "Los anillos de Saturno", "Las lunas de Júpiter", "La órbita de Marte", "El cometa Halley", 2],
["¿Qué tipo de roca se forma a partir de magma solidificado?", "Roca sedimentaria", "Roca metamórfica", "Roca ígnea", "Roca volcánica", 3],
["¿Qué gas constituye la mayor parte del aire que respiramos?", "Oxígeno", "Nitrógeno", "Dióxido de carbono", "Hidrógeno", 2],
["¿Qué órgano del cuerpo humano se encarga de procesar los alimentos?", "Estómago", "Hígado", "Páncreas", "Intestino delgado", 1],
["¿Qué científico es conocido por su trabajo con la electricidad y el magnetismo?", "Isaac Newton", "Nikola Tesla", "Charles Darwin", "Max Planck", 2],
["¿Qué fenómeno natural se mide en la escala de Richter?", "Tsunamis", "Huracanes", "Terremotos", "Erupciones volcánicas", 3],
["¿Cuál es el elemento químico más ligero?", "Helio", "Oxígeno", "Hidrógeno", "Litio", 3],
["¿Qué forma tiene la Vía Láctea?", "Espiral", "Elíptica", "Irregular", "Circular", 1],
["¿Qué glándula produce la hormona insulina?", "Tiroides", "Hígado", "Páncreas", "Glándulas suprarrenales", 3],
["¿Qué parte del ojo humano controla la cantidad de luz que entra?", "Córnea", "Iris", "Pupila", "Retina", 2],
["¿Qué planeta tiene el mayor número de lunas?", "Júpiter", "Saturno", "Neptuno", "Urano", 1],
["¿Qué tipo de célula carece de núcleo?", "Célula animal", "Célula vegetal", "Célula procariota", "Célula eucariota", 3],
["¿Qué científico propuso la teoría de la selección natural?", "Isaac Newton", "Charles Darwin", "Gregor Mendel", "Stephen Hawking", 2],
["¿Qué instrumento mide la presión atmosférica?", "Termómetro", "Barómetro", "Higrómetro", "Anemómetro", 2],
["¿Qué tipo de energía se almacena en los alimentos?", "Energía cinética", "Energía potencial", "Energía química", "Energía térmica", 3],
["¿Qué tipo de estrella es el Sol?", "Enana blanca", "Gigante roja", "Supernova", "Enana amarilla", 4],
["¿Qué significa 'H2O'?", "Hidrógeno y ozono", "Dióxido de hidrógeno", "Agua", "Peróxido de hidrógeno", 3],
["¿Qué es un agujero negro?", "Un objeto muy frío", "Un vacío sin materia", "Una región con gravedad extrema", "Un tipo de estrella", 3],
["¿Qué proceso convierte los desechos orgánicos en energía?", "Fotosíntesis", "Digestión anaeróbica", "Fermentación", "Transpiración", 2],
["¿Cuál es el planeta más frío del sistema solar?", "Urano", "Neptuno", "Saturno", "Plutón", 1],
["¿Qué componente del sistema nervioso transmite señales eléctricas?", "Músculos", "Neuronas", "Hormonas", "Glóbulos blancos", 2],
["¿Qué teoría explica el origen del universo?", "Teoría de la relatividad", "Teoría del Big Bang", "Teoría cuántica", "Teoría de cuerdas", 2],
["¿Qué organismo causa el resfriado común?", "Bacterias", "Virus", "Hongos", "Parásitos", 2],
["¿Qué se estudia en la química orgánica?", "Compuestos inorgánicos", "Reacciones nucleares", "Compuestos de carbono", "Propiedades del agua", 3],
["¿Qué fuerza actúa sobre los objetos en caída libre?", "Fuerza centrífuga", "Fuerza de gravedad", "Fuerza magnética", "Fuerza elástica", 2],
["¿Qué proteína transporta oxígeno en la sangre?", "Insulina", "Hemoglobina", "Colágeno", "Glucógeno", 2],
["¿Qué animal puede regenerar partes de su cuerpo?", "Tiburón", "Estrella de mar", "Camaleón", "Lombriz de tierra", 2],
["¿Qué parte de la célula produce energía?", "Núcleo", "Mitocondria", "Ribosoma", "Cloroplasto", 2],
["¿Qué tipo de roca se forma bajo alta presión y temperatura?", "Ígnea", "Metamórfica", "Sedimentaria", "Volcánica", 2],
["¿Qué enfermedad se combate con la vacuna BCG?", "Malaria", "Tuberculosis", "Sarampión", "Varicela", 2],
["¿Qué sistema del cuerpo humano incluye el corazón y los vasos sanguíneos?", "Sistema digestivo", "Sistema nervioso", "Sistema circulatorio", "Sistema respiratorio", 3],
["¿Qué fenómeno ocurre cuando la Luna bloquea la luz del Sol?", "Eclipse solar", "Eclipse lunar", "Solsticio", "Equinoccio", 1]
]